Fix build script on Windows
The current script actually can't work on Windows because
split() expects a regex. With current code, Java complains

java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^

Thus we fix the issue by plain regex literal.

Signed-off-by: Bo Zhang <zhangbodut@gmail.com>